[store]
dir = "target/nextest"

[profile.default]
retries = 0
fail-fast = false
test-threads = "num-cpus"

[[profile.default.overrides]]
filter = 'test(catalog_paths_exist_when_env_set)'
ignore = true

[profile.ci]
retries = { backoff = "fixed", count = 1, delay-ms = 500 }
fail-fast = true

[[profile.ci.overrides]]
filter = 'test(catalog_paths_exist_when_env_set)'
ignore = true
